// LOCALHOST

### Get all contacts
GET http://localhost:3000/contacts
### Get contact 1 by ID
GET http://localhost:3000/contacts/66f8baa464be7513e2877ea4
### Get contact 2 by ID
GET http://localhost:3000/contacts/66f8baa464be7513e2877ea5
### Get contact 3 by ID
GET http://localhost:3000/contacts/66f8baa464be7513e2877ea6
### Create contact1
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Trudee",
        "lastName": "Rummler",
        "email": "trudee@gmail.com",
        "favoriteColor": "Green",
        "birthday": "03/22/95"
    }

### Create contact2
POST http://localhost:3000/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Bonnee",
        "lastName": "Rummler",
        "email": "bonnee@gmail.com",
        "favoriteColor": "Blue",
        "birthday": "04/2/95"
    }

### Update contact (change Kai's name to his middle name "Christopher")
PUT http://localhost:3000/contacts/67005b2240a7808a8e786177 HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Kai",
        "lastName": "Rummler",
        "email": "kairummler@gmail.com",
        "favoriteColor": "Blue",
        "birthday": "07/19/01"
    } 
### Delete contact
DELETE http://localhost:3000/contacts/67005b4140a7808a8e786179 HTTP/1.1
  
// PRODUCTION Deploy
### Get all contacts
GET https://cse341-fall24-2sba.onrender.com/contacts
### Get contact 1
GET https://cse341-fall24-2sba.onrender.com/contacts/66f8baa464be7513e2877ea4
### Get contact 2
GET https://cse341-fall24-2sba.onrender.com/contacts/66f8baa464be7513e2877ea5
### Get contact 3
GET https://cse341-fall24-2sba.onrender.com/contacts/66f8baa464be7513e2877ea6
### Create contact 1
POST https://cse341-fall24-2sba.onrender.com/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Trudee",
        "lastName": "Rummler",
        "email": "trudee@gmail.com",
        "favoriteColor": "Green",
        "birthday": "03/22/95"
    }
### Create contact 2
POST https://cse341-fall24-2sba.onrender.com/contacts HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Bonnee",
        "lastName": "Rummler",
        "email": "bonnee@gmail.com",
        "favoriteColor": "Blue",
        "birthday": "04/2/95"
    }
### Update contact - change Kai's name to his middle name "Christopher"
PUT https://cse341-fall24-2sba.onrender.com/contacts/66f8baa464be7513e2877ea6 HTTP/1.1
Content-Type: application/json

    {
        "firstName": "Kai",
        "lastName": "Rummler",
        "email": "kairummler@gmail.com",
        "favoriteColor": "Blue",
        "birthday": "07/19/01"
    } 
### Delete contact
DELETE https://cse341-fall24-2sba.onrender.com/contacts/67005b2240a7808a8e786177 HTTP/1.1